#pragma once

#include "dy/error.h"

#define DY_APPINFO_APP_OWNER_LEN 16
#define DY_APPINFO_APP_NAME_LEN 16
#define DY_APPINFO_APP_AUTH_LEN 32

#define DY_APPINFO_APP_ARCH_LEN 16
#define DY_APPINFO_APP_ID_LEN 64

typedef struct {
    uint8_t major;
    uint8_t minor;
    uint8_t patch;
    uint8_t alpha;
} dy_appinfo_ver_t;

typedef struct {
    dy_appinfo_ver_t ver;

    char *owner;
    char *name;
    char *auth; // authentication token

    char *arch; // architecture; set by dy_appinfo_set
    char *id;   // concatenated info; generated by dy_appinfo_set
    char *ua;   // web user agent; generated by dy_appinfo_set
} dy_appinfo_info_t;


dy_err_t dy_appinfo_set(dy_appinfo_info_t *inf);

dy_err_t dy_appinfo_get(dy_appinfo_info_t *);
