version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: cronus_dev
    container_name: cronus_dev_app
    user: 1000:1000
    volumes:
      - ./src:/home/application
    ports:
      - 8000:8000
    environment:
      DEBUG: 1
