version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - target: 9000
        published: ${EXT_PORT}
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
