#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME = cronus
EXTRA_COMPONENT_DIRS := ${AESPL_PATH} ${AGFXL_PATH}

include $(IDF_PATH)/make/project.mk
