#ifndef CRONUS_MODE_H
#define CRONUS_MODE_H

typedef enum {
    APP_MODE_SHOW_MIN,
    APP_MODE_SHOW_TIME,
    APP_MODE_SHOW_DATE,
    APP_MODE_SHOW_DOW,
    APP_MODE_SHOW_AMBIENT_TEMP,
    APP_MODE_SHOW_WEATHER_TEMP,
    APP_MODE_SHOW_MAX,
    APP_MODE_SETTINGS_MIN,
    APP_MODE_SETTINGS_TIME_HOUR,
    APP_MODE_SETTINGS_TIME_MINUTE,
    APP_MODE_SETTINGS_DATE_DAY,
    APP_MODE_SETTINGS_DATE_MONTH,
    APP_MODE_SETTINGS_DATE_DOW,
    APP_MODE_SETTINGS_DATE_YEAR,
    APP_MODE_SETTINGS_ALARM_HOUR,
    APP_MODE_SETTINGS_ALARM_MINUTE,
    APP_MODE_SETTINGS_BRIGHTNESS,
    APP_MODE_SETTINGS_MAX,
} app_mode_t;

#endif //CRONUS_MODE_H
