version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: cronus_prod
    container_name: cronus_prod_app
    user: 1000:1000
    ports:
      - 9001:8000
    environment:
      DEBUG: 0
